"""Binary data for :mod:`roadnetwork_rg`"""

__all__ = ["colour_palette"]

from importlib import resources

colour_palette = resources.open_binary(__name__, 'colourmap.palette').read()
"""colour palette for images generated by :meth:`.HeightMap.generate` with levels"""
